DROP TRIGGER IF EXISTS trg_ai_external_evidence_intake_audit_events_append_only
ON ai_transparency_external_evidence_intake_audit_events;
DROP TRIGGER IF EXISTS trg_ai_external_evidence_intakes_append_only
ON ai_transparency_external_evidence_intakes;
DROP FUNCTION IF EXISTS reject_ai_transparency_external_evidence_intake_mutation();
DROP TABLE IF EXISTS ai_transparency_external_evidence_intake_audit_events;
DROP TABLE IF EXISTS ai_transparency_external_evidence_intakes;
