// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `append_interleaved_from_buffer`, `append_interleaved_samples`, `audio_extension_hint_from_bytes`, `decode_audio_to_wav`, `default_ai_flags`, `from_core`, `into_core_format`, `into_core_payload`, `is_wav_bytes`, `issue_mode_label`, `media_type_label`, `mobile_extract_result_from_decoded`, `normalize_audio_to_wav`, `operation_failed`, `parse_hex_16`, `parse_media_type`, `parse_watermark_uid`, `sha256_hex`, `write_interleaved_wav`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `into_mobile_extract_result`

Future<MobileImageResult> embedImageForMobile({
  required List<int> imageBytes,
  required MobileMediaPayload payload,
  required MobileImageOutputFormat outputFormat,
  required bool allowRewrite,
}) => RustLib.instance.api.crateApiEmbedImageForMobile(
  imageBytes: imageBytes,
  payload: payload,
  outputFormat: outputFormat,
  allowRewrite: allowRewrite,
);

Future<MobileExtractResult> extractImageForMobile({
  required List<int> imageBytes,
}) =>
    RustLib.instance.api.crateApiExtractImageForMobile(imageBytes: imageBytes);

Future<MobileExtractResult> extractImageReadonlyCandidateForMobile({
  required List<int> imageBytes,
}) => RustLib.instance.api.crateApiExtractImageReadonlyCandidateForMobile(
  imageBytes: imageBytes,
);

Future<MobileExtractResult?> detectExistingImageForMobile({
  required List<int> imageBytes,
}) => RustLib.instance.api.crateApiDetectExistingImageForMobile(
  imageBytes: imageBytes,
);

Future<MobileAudioResult> embedAudioWavForMobile({
  required List<int> audioBytes,
  required MobileMediaPayload payload,
  required bool allowRewrite,
}) => RustLib.instance.api.crateApiEmbedAudioWavForMobile(
  audioBytes: audioBytes,
  payload: payload,
  allowRewrite: allowRewrite,
);

Future<MobileExtractResult> extractAudioWavForMobile({
  required List<int> audioBytes,
}) => RustLib.instance.api.crateApiExtractAudioWavForMobile(
  audioBytes: audioBytes,
);

Future<MobileExtractResult> extractAudioWavReadonlyCandidateForMobile({
  required List<int> audioBytes,
}) => RustLib.instance.api.crateApiExtractAudioWavReadonlyCandidateForMobile(
  audioBytes: audioBytes,
);

Future<MobileV3InternalQaWriteResult> embedV3InternalQaForMobile({
  required List<int> mediaBytes,
  required String mediaType,
  required String watermarkUid,
}) => RustLib.instance.api.crateApiEmbedV3InternalQaForMobile(
  mediaBytes: mediaBytes,
  mediaType: mediaType,
  watermarkUid: watermarkUid,
);

Future<MobileExtractResult> decodeV3ReadonlyFixtureForMobile({
  required List<int> payloadBytes,
  required String mediaType,
}) => RustLib.instance.api.crateApiDecodeV3ReadonlyFixtureForMobile(
  payloadBytes: payloadBytes,
  mediaType: mediaType,
);

Future<MobileExtractResult> decodeV3ReadonlyMediaFixtureForMobile({
  required List<int> mediaBytes,
  required String mediaType,
}) => RustLib.instance.api.crateApiDecodeV3ReadonlyMediaFixtureForMobile(
  mediaBytes: mediaBytes,
  mediaType: mediaType,
);

abstract class IntoMobileExtractResult {
  Future<MobileExtractResult> intoMobileExtractResult();
}

class MobileAudioResult {
  final Uint8List bytes;
  final String watermarkUid;
  final String sha256;

  const MobileAudioResult({
    required this.bytes,
    required this.watermarkUid,
    required this.sha256,
  });

  @override
  int get hashCode => bytes.hashCode ^ watermarkUid.hashCode ^ sha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobileAudioResult &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          watermarkUid == other.watermarkUid &&
          sha256 == other.sha256;
}

class MobileExtractResult {
  final String watermarkUid;
  final BigInt timestamp;
  final String deviceIdHex;
  final String fileHashHex;
  final String? parentWatermarkUid;
  final int revision;
  final int payloadProtocolVersion;
  final int payloadBytesLength;
  final String watermarkIdIssueMode;
  final String mediaType;
  final String payloadAuthStatus;

  const MobileExtractResult({
    required this.watermarkUid,
    required this.timestamp,
    required this.deviceIdHex,
    required this.fileHashHex,
    this.parentWatermarkUid,
    required this.revision,
    required this.payloadProtocolVersion,
    required this.payloadBytesLength,
    required this.watermarkIdIssueMode,
    required this.mediaType,
    required this.payloadAuthStatus,
  });

  @override
  int get hashCode =>
      watermarkUid.hashCode ^
      timestamp.hashCode ^
      deviceIdHex.hashCode ^
      fileHashHex.hashCode ^
      parentWatermarkUid.hashCode ^
      revision.hashCode ^
      payloadProtocolVersion.hashCode ^
      payloadBytesLength.hashCode ^
      watermarkIdIssueMode.hashCode ^
      mediaType.hashCode ^
      payloadAuthStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobileExtractResult &&
          runtimeType == other.runtimeType &&
          watermarkUid == other.watermarkUid &&
          timestamp == other.timestamp &&
          deviceIdHex == other.deviceIdHex &&
          fileHashHex == other.fileHashHex &&
          parentWatermarkUid == other.parentWatermarkUid &&
          revision == other.revision &&
          payloadProtocolVersion == other.payloadProtocolVersion &&
          payloadBytesLength == other.payloadBytesLength &&
          watermarkIdIssueMode == other.watermarkIdIssueMode &&
          mediaType == other.mediaType &&
          payloadAuthStatus == other.payloadAuthStatus;
}

enum MobileImageOutputFormat { png, jpeg, webP }

class MobileImageResult {
  final Uint8List bytes;
  final String watermarkUid;
  final String sha256;
  final MobileImageOutputFormat format;

  const MobileImageResult({
    required this.bytes,
    required this.watermarkUid,
    required this.sha256,
    required this.format,
  });

  @override
  int get hashCode =>
      bytes.hashCode ^
      watermarkUid.hashCode ^
      sha256.hashCode ^
      format.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobileImageResult &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          watermarkUid == other.watermarkUid &&
          sha256 == other.sha256 &&
          format == other.format;
}

class MobileMediaPayload {
  final String creatorIdentity;
  final String deviceIdentity;
  final Uint8List mediaBytes;
  final BigInt timestamp;
  final String? reservedWatermarkUid;
  final String? registryProofHash;
  final String? parentWatermarkUid;
  final int revision;
  final String? mediaType;

  const MobileMediaPayload({
    required this.creatorIdentity,
    required this.deviceIdentity,
    required this.mediaBytes,
    required this.timestamp,
    this.reservedWatermarkUid,
    this.registryProofHash,
    this.parentWatermarkUid,
    required this.revision,
    this.mediaType,
  });

  @override
  int get hashCode =>
      creatorIdentity.hashCode ^
      deviceIdentity.hashCode ^
      mediaBytes.hashCode ^
      timestamp.hashCode ^
      reservedWatermarkUid.hashCode ^
      registryProofHash.hashCode ^
      parentWatermarkUid.hashCode ^
      revision.hashCode ^
      mediaType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobileMediaPayload &&
          runtimeType == other.runtimeType &&
          creatorIdentity == other.creatorIdentity &&
          deviceIdentity == other.deviceIdentity &&
          mediaBytes == other.mediaBytes &&
          timestamp == other.timestamp &&
          reservedWatermarkUid == other.reservedWatermarkUid &&
          registryProofHash == other.registryProofHash &&
          parentWatermarkUid == other.parentWatermarkUid &&
          revision == other.revision &&
          mediaType == other.mediaType;
}

class MobileV3InternalQaWriteResult {
  final Uint8List bytes;
  final String watermarkUid;
  final String sha256;
  final String mediaType;
  final int payloadProtocolVersion;
  final int payloadBytesLength;
  final String payloadAuthStatus;
  final String watermarkIdIssueMode;
  final String mediaPayloadRole;

  const MobileV3InternalQaWriteResult({
    required this.bytes,
    required this.watermarkUid,
    required this.sha256,
    required this.mediaType,
    required this.payloadProtocolVersion,
    required this.payloadBytesLength,
    required this.payloadAuthStatus,
    required this.watermarkIdIssueMode,
    required this.mediaPayloadRole,
  });

  @override
  int get hashCode =>
      bytes.hashCode ^
      watermarkUid.hashCode ^
      sha256.hashCode ^
      mediaType.hashCode ^
      payloadProtocolVersion.hashCode ^
      payloadBytesLength.hashCode ^
      payloadAuthStatus.hashCode ^
      watermarkIdIssueMode.hashCode ^
      mediaPayloadRole.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobileV3InternalQaWriteResult &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          watermarkUid == other.watermarkUid &&
          sha256 == other.sha256 &&
          mediaType == other.mediaType &&
          payloadProtocolVersion == other.payloadProtocolVersion &&
          payloadBytesLength == other.payloadBytesLength &&
          payloadAuthStatus == other.payloadAuthStatus &&
          watermarkIdIssueMode == other.watermarkIdIssueMode &&
          mediaPayloadRole == other.mediaPayloadRole;
}

@freezed
sealed class MobileWatermarkError
    with _$MobileWatermarkError
    implements FrbException {
  const MobileWatermarkError._();

  const factory MobileWatermarkError.invalidPayload({
    required String code,
    required String message,
  }) = MobileWatermarkError_InvalidPayload;
  const factory MobileWatermarkError.operationFailed({
    required String code,
    required String message,
    String? existingUid,
  }) = MobileWatermarkError_OperationFailed;
}
