// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `default_ai_flags`, `fixed_array`, `into_core_format`, `into_core_payload`, `sha256_hex`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `into_mobile_extract_result`

Future<MobileImageResult> embedImageForMobile({
  required List<int> imageBytes,
  required MobileMediaPayload payload,
  required MobileImageOutputFormat outputFormat,
  required bool allowRewrite,
}) => RustLib.instance.api.crateApiEmbedImageForMobile(
  imageBytes: imageBytes,
  payload: payload,
  outputFormat: outputFormat,
  allowRewrite: allowRewrite,
);

Future<MobileExtractResult> extractImageForMobile({
  required List<int> imageBytes,
}) =>
    RustLib.instance.api.crateApiExtractImageForMobile(imageBytes: imageBytes);

abstract class IntoMobileExtractResult {
  Future<MobileExtractResult> intoMobileExtractResult();
}

class MobileExtractResult {
  final String watermarkUid;
  final BigInt timestamp;
  final String deviceIdHex;
  final String fileHashHex;

  const MobileExtractResult({
    required this.watermarkUid,
    required this.timestamp,
    required this.deviceIdHex,
    required this.fileHashHex,
  });

  @override
  int get hashCode =>
      watermarkUid.hashCode ^
      timestamp.hashCode ^
      deviceIdHex.hashCode ^
      fileHashHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobileExtractResult &&
          runtimeType == other.runtimeType &&
          watermarkUid == other.watermarkUid &&
          timestamp == other.timestamp &&
          deviceIdHex == other.deviceIdHex &&
          fileHashHex == other.fileHashHex;
}

enum MobileImageOutputFormat { png, jpeg, webP }

class MobileImageResult {
  final Uint8List bytes;
  final String watermarkUid;
  final String sha256;
  final MobileImageOutputFormat format;

  const MobileImageResult({
    required this.bytes,
    required this.watermarkUid,
    required this.sha256,
    required this.format,
  });

  @override
  int get hashCode =>
      bytes.hashCode ^
      watermarkUid.hashCode ^
      sha256.hashCode ^
      format.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobileImageResult &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          watermarkUid == other.watermarkUid &&
          sha256 == other.sha256 &&
          format == other.format;
}

class MobileMediaPayload {
  final Uint8List userSeed;
  final BigInt timestamp;
  final Uint8List deviceId;
  final Uint8List fileHash;

  const MobileMediaPayload({
    required this.userSeed,
    required this.timestamp,
    required this.deviceId,
    required this.fileHash,
  });

  @override
  int get hashCode =>
      userSeed.hashCode ^
      timestamp.hashCode ^
      deviceId.hashCode ^
      fileHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobileMediaPayload &&
          runtimeType == other.runtimeType &&
          userSeed == other.userSeed &&
          timestamp == other.timestamp &&
          deviceId == other.deviceId &&
          fileHash == other.fileHash;
}

@freezed
sealed class MobileWatermarkError
    with _$MobileWatermarkError
    implements FrbException {
  const MobileWatermarkError._();

  const factory MobileWatermarkError.invalidPayload(String field0) =
      MobileWatermarkError_InvalidPayload;
  const factory MobileWatermarkError.operationFailed(String field0) =
      MobileWatermarkError_OperationFailed;
}
