// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 193433128;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'hidden_shield_mobile_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<MobileImageResult> crateApiEmbedImageForMobile({
    required List<int> imageBytes,
    required MobileMediaPayload payload,
    required MobileImageOutputFormat outputFormat,
    required bool allowRewrite,
  });

  Future<MobileExtractResult> crateApiExtractImageForMobile({
    required List<int> imageBytes,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<MobileImageResult> crateApiEmbedImageForMobile({
    required List<int> imageBytes,
    required MobileMediaPayload payload,
    required MobileImageOutputFormat outputFormat,
    required bool allowRewrite,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_box_autoadd_mobile_media_payload(payload, serializer);
          sse_encode_mobile_image_output_format(outputFormat, serializer);
          sse_encode_bool(allowRewrite, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mobile_image_result,
          decodeErrorData: sse_decode_mobile_watermark_error,
        ),
        constMeta: kCrateApiEmbedImageForMobileConstMeta,
        argValues: [imageBytes, payload, outputFormat, allowRewrite],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEmbedImageForMobileConstMeta =>
      const TaskConstMeta(
        debugName: "embed_image_for_mobile",
        argNames: ["imageBytes", "payload", "outputFormat", "allowRewrite"],
      );

  @override
  Future<MobileExtractResult> crateApiExtractImageForMobile({
    required List<int> imageBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mobile_extract_result,
          decodeErrorData: sse_decode_mobile_watermark_error,
        ),
        constMeta: kCrateApiExtractImageForMobileConstMeta,
        argValues: [imageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExtractImageForMobileConstMeta =>
      const TaskConstMeta(
        debugName: "extract_image_for_mobile",
        argNames: ["imageBytes"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  IntoMobileExtractResult dco_decode_TraitDef_IntoMobileExtractResult(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  MobileMediaPayload dco_decode_box_autoadd_mobile_media_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mobile_media_payload(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MobileExtractResult dco_decode_mobile_extract_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MobileExtractResult(
      watermarkUid: dco_decode_String(arr[0]),
      timestamp: dco_decode_u_64(arr[1]),
      deviceIdHex: dco_decode_String(arr[2]),
      fileHashHex: dco_decode_String(arr[3]),
    );
  }

  @protected
  MobileImageOutputFormat dco_decode_mobile_image_output_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MobileImageOutputFormat.values[raw as int];
  }

  @protected
  MobileImageResult dco_decode_mobile_image_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MobileImageResult(
      bytes: dco_decode_list_prim_u_8_strict(arr[0]),
      watermarkUid: dco_decode_String(arr[1]),
      sha256: dco_decode_String(arr[2]),
      format: dco_decode_mobile_image_output_format(arr[3]),
    );
  }

  @protected
  MobileMediaPayload dco_decode_mobile_media_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MobileMediaPayload(
      userSeed: dco_decode_list_prim_u_8_strict(arr[0]),
      timestamp: dco_decode_u_64(arr[1]),
      deviceId: dco_decode_list_prim_u_8_strict(arr[2]),
      fileHash: dco_decode_list_prim_u_8_strict(arr[3]),
    );
  }

  @protected
  MobileWatermarkError dco_decode_mobile_watermark_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return MobileWatermarkError_InvalidPayload(dco_decode_String(raw[1]));
      case 1:
        return MobileWatermarkError_OperationFailed(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  MobileMediaPayload sse_decode_box_autoadd_mobile_media_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mobile_media_payload(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MobileExtractResult sse_decode_mobile_extract_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_watermarkUid = sse_decode_String(deserializer);
    var var_timestamp = sse_decode_u_64(deserializer);
    var var_deviceIdHex = sse_decode_String(deserializer);
    var var_fileHashHex = sse_decode_String(deserializer);
    return MobileExtractResult(
      watermarkUid: var_watermarkUid,
      timestamp: var_timestamp,
      deviceIdHex: var_deviceIdHex,
      fileHashHex: var_fileHashHex,
    );
  }

  @protected
  MobileImageOutputFormat sse_decode_mobile_image_output_format(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MobileImageOutputFormat.values[inner];
  }

  @protected
  MobileImageResult sse_decode_mobile_image_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_watermarkUid = sse_decode_String(deserializer);
    var var_sha256 = sse_decode_String(deserializer);
    var var_format = sse_decode_mobile_image_output_format(deserializer);
    return MobileImageResult(
      bytes: var_bytes,
      watermarkUid: var_watermarkUid,
      sha256: var_sha256,
      format: var_format,
    );
  }

  @protected
  MobileMediaPayload sse_decode_mobile_media_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userSeed = sse_decode_list_prim_u_8_strict(deserializer);
    var var_timestamp = sse_decode_u_64(deserializer);
    var var_deviceId = sse_decode_list_prim_u_8_strict(deserializer);
    var var_fileHash = sse_decode_list_prim_u_8_strict(deserializer);
    return MobileMediaPayload(
      userSeed: var_userSeed,
      timestamp: var_timestamp,
      deviceId: var_deviceId,
      fileHash: var_fileHash,
    );
  }

  @protected
  MobileWatermarkError sse_decode_mobile_watermark_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return MobileWatermarkError_InvalidPayload(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return MobileWatermarkError_OperationFailed(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_mobile_media_payload(
    MobileMediaPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mobile_media_payload(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_mobile_extract_result(
    MobileExtractResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.watermarkUid, serializer);
    sse_encode_u_64(self.timestamp, serializer);
    sse_encode_String(self.deviceIdHex, serializer);
    sse_encode_String(self.fileHashHex, serializer);
  }

  @protected
  void sse_encode_mobile_image_output_format(
    MobileImageOutputFormat self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_mobile_image_result(
    MobileImageResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
    sse_encode_String(self.watermarkUid, serializer);
    sse_encode_String(self.sha256, serializer);
    sse_encode_mobile_image_output_format(self.format, serializer);
  }

  @protected
  void sse_encode_mobile_media_payload(
    MobileMediaPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.userSeed, serializer);
    sse_encode_u_64(self.timestamp, serializer);
    sse_encode_list_prim_u_8_strict(self.deviceId, serializer);
    sse_encode_list_prim_u_8_strict(self.fileHash, serializer);
  }

  @protected
  void sse_encode_mobile_watermark_error(
    MobileWatermarkError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case MobileWatermarkError_InvalidPayload(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case MobileWatermarkError_OperationFailed(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
