// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -428348159;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'hidden_shield_mobile_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<MobileExtractResult> crateApiDecodeV3ReadonlyFixtureForMobile({
    required List<int> payloadBytes,
    required String mediaType,
  });

  Future<MobileExtractResult> crateApiDecodeV3ReadonlyMediaFixtureForMobile({
    required List<int> mediaBytes,
    required String mediaType,
  });

  Future<MobileExtractResult?> crateApiDetectExistingImageForMobile({
    required List<int> imageBytes,
  });

  Future<MobileAudioResult> crateApiEmbedAudioWavForMobile({
    required List<int> audioBytes,
    required MobileMediaPayload payload,
    required bool allowRewrite,
  });

  Future<MobileImageResult> crateApiEmbedImageForMobile({
    required List<int> imageBytes,
    required MobileMediaPayload payload,
    required MobileImageOutputFormat outputFormat,
    required bool allowRewrite,
  });

  Future<MobileV3InternalQaWriteResult> crateApiEmbedV3InternalQaForMobile({
    required List<int> mediaBytes,
    required String mediaType,
    required String watermarkUid,
  });

  Future<MobileExtractResult> crateApiExtractAudioWavForMobile({
    required List<int> audioBytes,
  });

  Future<MobileExtractResult>
  crateApiExtractAudioWavReadonlyCandidateForMobile({
    required List<int> audioBytes,
  });

  Future<MobileExtractResult> crateApiExtractImageForMobile({
    required List<int> imageBytes,
  });

  Future<MobileExtractResult> crateApiExtractImageReadonlyCandidateForMobile({
    required List<int> imageBytes,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<MobileExtractResult> crateApiDecodeV3ReadonlyFixtureForMobile({
    required List<int> payloadBytes,
    required String mediaType,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(payloadBytes, serializer);
          sse_encode_String(mediaType, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mobile_extract_result,
          decodeErrorData: sse_decode_mobile_watermark_error,
        ),
        constMeta: kCrateApiDecodeV3ReadonlyFixtureForMobileConstMeta,
        argValues: [payloadBytes, mediaType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDecodeV3ReadonlyFixtureForMobileConstMeta =>
      const TaskConstMeta(
        debugName: "decode_v3_readonly_fixture_for_mobile",
        argNames: ["payloadBytes", "mediaType"],
      );

  @override
  Future<MobileExtractResult> crateApiDecodeV3ReadonlyMediaFixtureForMobile({
    required List<int> mediaBytes,
    required String mediaType,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(mediaBytes, serializer);
          sse_encode_String(mediaType, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mobile_extract_result,
          decodeErrorData: sse_decode_mobile_watermark_error,
        ),
        constMeta: kCrateApiDecodeV3ReadonlyMediaFixtureForMobileConstMeta,
        argValues: [mediaBytes, mediaType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDecodeV3ReadonlyMediaFixtureForMobileConstMeta =>
      const TaskConstMeta(
        debugName: "decode_v3_readonly_media_fixture_for_mobile",
        argNames: ["mediaBytes", "mediaType"],
      );

  @override
  Future<MobileExtractResult?> crateApiDetectExistingImageForMobile({
    required List<int> imageBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_mobile_extract_result,
          decodeErrorData: sse_decode_mobile_watermark_error,
        ),
        constMeta: kCrateApiDetectExistingImageForMobileConstMeta,
        argValues: [imageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDetectExistingImageForMobileConstMeta =>
      const TaskConstMeta(
        debugName: "detect_existing_image_for_mobile",
        argNames: ["imageBytes"],
      );

  @override
  Future<MobileAudioResult> crateApiEmbedAudioWavForMobile({
    required List<int> audioBytes,
    required MobileMediaPayload payload,
    required bool allowRewrite,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(audioBytes, serializer);
          sse_encode_box_autoadd_mobile_media_payload(payload, serializer);
          sse_encode_bool(allowRewrite, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mobile_audio_result,
          decodeErrorData: sse_decode_mobile_watermark_error,
        ),
        constMeta: kCrateApiEmbedAudioWavForMobileConstMeta,
        argValues: [audioBytes, payload, allowRewrite],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEmbedAudioWavForMobileConstMeta =>
      const TaskConstMeta(
        debugName: "embed_audio_wav_for_mobile",
        argNames: ["audioBytes", "payload", "allowRewrite"],
      );

  @override
  Future<MobileImageResult> crateApiEmbedImageForMobile({
    required List<int> imageBytes,
    required MobileMediaPayload payload,
    required MobileImageOutputFormat outputFormat,
    required bool allowRewrite,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          sse_encode_box_autoadd_mobile_media_payload(payload, serializer);
          sse_encode_mobile_image_output_format(outputFormat, serializer);
          sse_encode_bool(allowRewrite, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mobile_image_result,
          decodeErrorData: sse_decode_mobile_watermark_error,
        ),
        constMeta: kCrateApiEmbedImageForMobileConstMeta,
        argValues: [imageBytes, payload, outputFormat, allowRewrite],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEmbedImageForMobileConstMeta =>
      const TaskConstMeta(
        debugName: "embed_image_for_mobile",
        argNames: ["imageBytes", "payload", "outputFormat", "allowRewrite"],
      );

  @override
  Future<MobileV3InternalQaWriteResult> crateApiEmbedV3InternalQaForMobile({
    required List<int> mediaBytes,
    required String mediaType,
    required String watermarkUid,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(mediaBytes, serializer);
          sse_encode_String(mediaType, serializer);
          sse_encode_String(watermarkUid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mobile_v_3_internal_qa_write_result,
          decodeErrorData: sse_decode_mobile_watermark_error,
        ),
        constMeta: kCrateApiEmbedV3InternalQaForMobileConstMeta,
        argValues: [mediaBytes, mediaType, watermarkUid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEmbedV3InternalQaForMobileConstMeta =>
      const TaskConstMeta(
        debugName: "embed_v3_internal_qa_for_mobile",
        argNames: ["mediaBytes", "mediaType", "watermarkUid"],
      );

  @override
  Future<MobileExtractResult> crateApiExtractAudioWavForMobile({
    required List<int> audioBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(audioBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mobile_extract_result,
          decodeErrorData: sse_decode_mobile_watermark_error,
        ),
        constMeta: kCrateApiExtractAudioWavForMobileConstMeta,
        argValues: [audioBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExtractAudioWavForMobileConstMeta =>
      const TaskConstMeta(
        debugName: "extract_audio_wav_for_mobile",
        argNames: ["audioBytes"],
      );

  @override
  Future<MobileExtractResult>
  crateApiExtractAudioWavReadonlyCandidateForMobile({
    required List<int> audioBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(audioBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mobile_extract_result,
          decodeErrorData: sse_decode_mobile_watermark_error,
        ),
        constMeta: kCrateApiExtractAudioWavReadonlyCandidateForMobileConstMeta,
        argValues: [audioBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiExtractAudioWavReadonlyCandidateForMobileConstMeta =>
      const TaskConstMeta(
        debugName: "extract_audio_wav_readonly_candidate_for_mobile",
        argNames: ["audioBytes"],
      );

  @override
  Future<MobileExtractResult> crateApiExtractImageForMobile({
    required List<int> imageBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mobile_extract_result,
          decodeErrorData: sse_decode_mobile_watermark_error,
        ),
        constMeta: kCrateApiExtractImageForMobileConstMeta,
        argValues: [imageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExtractImageForMobileConstMeta =>
      const TaskConstMeta(
        debugName: "extract_image_for_mobile",
        argNames: ["imageBytes"],
      );

  @override
  Future<MobileExtractResult> crateApiExtractImageReadonlyCandidateForMobile({
    required List<int> imageBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(imageBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mobile_extract_result,
          decodeErrorData: sse_decode_mobile_watermark_error,
        ),
        constMeta: kCrateApiExtractImageReadonlyCandidateForMobileConstMeta,
        argValues: [imageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExtractImageReadonlyCandidateForMobileConstMeta =>
      const TaskConstMeta(
        debugName: "extract_image_readonly_candidate_for_mobile",
        argNames: ["imageBytes"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  IntoMobileExtractResult dco_decode_TraitDef_IntoMobileExtractResult(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  MobileExtractResult dco_decode_box_autoadd_mobile_extract_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mobile_extract_result(raw);
  }

  @protected
  MobileMediaPayload dco_decode_box_autoadd_mobile_media_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mobile_media_payload(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MobileAudioResult dco_decode_mobile_audio_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MobileAudioResult(
      bytes: dco_decode_list_prim_u_8_strict(arr[0]),
      watermarkUid: dco_decode_String(arr[1]),
      sha256: dco_decode_String(arr[2]),
    );
  }

  @protected
  MobileExtractResult dco_decode_mobile_extract_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return MobileExtractResult(
      watermarkUid: dco_decode_String(arr[0]),
      timestamp: dco_decode_u_64(arr[1]),
      deviceIdHex: dco_decode_String(arr[2]),
      fileHashHex: dco_decode_String(arr[3]),
      parentWatermarkUid: dco_decode_opt_String(arr[4]),
      revision: dco_decode_u_32(arr[5]),
      payloadProtocolVersion: dco_decode_u_32(arr[6]),
      payloadBytesLength: dco_decode_u_32(arr[7]),
      watermarkIdIssueMode: dco_decode_String(arr[8]),
      mediaType: dco_decode_String(arr[9]),
      payloadAuthStatus: dco_decode_String(arr[10]),
    );
  }

  @protected
  MobileImageOutputFormat dco_decode_mobile_image_output_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MobileImageOutputFormat.values[raw as int];
  }

  @protected
  MobileImageResult dco_decode_mobile_image_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MobileImageResult(
      bytes: dco_decode_list_prim_u_8_strict(arr[0]),
      watermarkUid: dco_decode_String(arr[1]),
      sha256: dco_decode_String(arr[2]),
      format: dco_decode_mobile_image_output_format(arr[3]),
    );
  }

  @protected
  MobileMediaPayload dco_decode_mobile_media_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return MobileMediaPayload(
      creatorIdentity: dco_decode_String(arr[0]),
      deviceIdentity: dco_decode_String(arr[1]),
      mediaBytes: dco_decode_list_prim_u_8_strict(arr[2]),
      timestamp: dco_decode_u_64(arr[3]),
      reservedWatermarkUid: dco_decode_opt_String(arr[4]),
      registryProofHash: dco_decode_opt_String(arr[5]),
      parentWatermarkUid: dco_decode_opt_String(arr[6]),
      revision: dco_decode_u_32(arr[7]),
      mediaType: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  MobileV3InternalQaWriteResult dco_decode_mobile_v_3_internal_qa_write_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return MobileV3InternalQaWriteResult(
      bytes: dco_decode_list_prim_u_8_strict(arr[0]),
      watermarkUid: dco_decode_String(arr[1]),
      sha256: dco_decode_String(arr[2]),
      mediaType: dco_decode_String(arr[3]),
      payloadProtocolVersion: dco_decode_u_32(arr[4]),
      payloadBytesLength: dco_decode_u_32(arr[5]),
      payloadAuthStatus: dco_decode_String(arr[6]),
      watermarkIdIssueMode: dco_decode_String(arr[7]),
      mediaPayloadRole: dco_decode_String(arr[8]),
    );
  }

  @protected
  MobileWatermarkError dco_decode_mobile_watermark_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return MobileWatermarkError_InvalidPayload(
          code: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      case 1:
        return MobileWatermarkError_OperationFailed(
          code: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
          existingUid: dco_decode_opt_String(raw[3]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  MobileExtractResult? dco_decode_opt_box_autoadd_mobile_extract_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_mobile_extract_result(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  MobileExtractResult sse_decode_box_autoadd_mobile_extract_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mobile_extract_result(deserializer));
  }

  @protected
  MobileMediaPayload sse_decode_box_autoadd_mobile_media_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mobile_media_payload(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MobileAudioResult sse_decode_mobile_audio_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_watermarkUid = sse_decode_String(deserializer);
    var var_sha256 = sse_decode_String(deserializer);
    return MobileAudioResult(
      bytes: var_bytes,
      watermarkUid: var_watermarkUid,
      sha256: var_sha256,
    );
  }

  @protected
  MobileExtractResult sse_decode_mobile_extract_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_watermarkUid = sse_decode_String(deserializer);
    var var_timestamp = sse_decode_u_64(deserializer);
    var var_deviceIdHex = sse_decode_String(deserializer);
    var var_fileHashHex = sse_decode_String(deserializer);
    var var_parentWatermarkUid = sse_decode_opt_String(deserializer);
    var var_revision = sse_decode_u_32(deserializer);
    var var_payloadProtocolVersion = sse_decode_u_32(deserializer);
    var var_payloadBytesLength = sse_decode_u_32(deserializer);
    var var_watermarkIdIssueMode = sse_decode_String(deserializer);
    var var_mediaType = sse_decode_String(deserializer);
    var var_payloadAuthStatus = sse_decode_String(deserializer);
    return MobileExtractResult(
      watermarkUid: var_watermarkUid,
      timestamp: var_timestamp,
      deviceIdHex: var_deviceIdHex,
      fileHashHex: var_fileHashHex,
      parentWatermarkUid: var_parentWatermarkUid,
      revision: var_revision,
      payloadProtocolVersion: var_payloadProtocolVersion,
      payloadBytesLength: var_payloadBytesLength,
      watermarkIdIssueMode: var_watermarkIdIssueMode,
      mediaType: var_mediaType,
      payloadAuthStatus: var_payloadAuthStatus,
    );
  }

  @protected
  MobileImageOutputFormat sse_decode_mobile_image_output_format(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MobileImageOutputFormat.values[inner];
  }

  @protected
  MobileImageResult sse_decode_mobile_image_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_watermarkUid = sse_decode_String(deserializer);
    var var_sha256 = sse_decode_String(deserializer);
    var var_format = sse_decode_mobile_image_output_format(deserializer);
    return MobileImageResult(
      bytes: var_bytes,
      watermarkUid: var_watermarkUid,
      sha256: var_sha256,
      format: var_format,
    );
  }

  @protected
  MobileMediaPayload sse_decode_mobile_media_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_creatorIdentity = sse_decode_String(deserializer);
    var var_deviceIdentity = sse_decode_String(deserializer);
    var var_mediaBytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_timestamp = sse_decode_u_64(deserializer);
    var var_reservedWatermarkUid = sse_decode_opt_String(deserializer);
    var var_registryProofHash = sse_decode_opt_String(deserializer);
    var var_parentWatermarkUid = sse_decode_opt_String(deserializer);
    var var_revision = sse_decode_u_32(deserializer);
    var var_mediaType = sse_decode_opt_String(deserializer);
    return MobileMediaPayload(
      creatorIdentity: var_creatorIdentity,
      deviceIdentity: var_deviceIdentity,
      mediaBytes: var_mediaBytes,
      timestamp: var_timestamp,
      reservedWatermarkUid: var_reservedWatermarkUid,
      registryProofHash: var_registryProofHash,
      parentWatermarkUid: var_parentWatermarkUid,
      revision: var_revision,
      mediaType: var_mediaType,
    );
  }

  @protected
  MobileV3InternalQaWriteResult sse_decode_mobile_v_3_internal_qa_write_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_watermarkUid = sse_decode_String(deserializer);
    var var_sha256 = sse_decode_String(deserializer);
    var var_mediaType = sse_decode_String(deserializer);
    var var_payloadProtocolVersion = sse_decode_u_32(deserializer);
    var var_payloadBytesLength = sse_decode_u_32(deserializer);
    var var_payloadAuthStatus = sse_decode_String(deserializer);
    var var_watermarkIdIssueMode = sse_decode_String(deserializer);
    var var_mediaPayloadRole = sse_decode_String(deserializer);
    return MobileV3InternalQaWriteResult(
      bytes: var_bytes,
      watermarkUid: var_watermarkUid,
      sha256: var_sha256,
      mediaType: var_mediaType,
      payloadProtocolVersion: var_payloadProtocolVersion,
      payloadBytesLength: var_payloadBytesLength,
      payloadAuthStatus: var_payloadAuthStatus,
      watermarkIdIssueMode: var_watermarkIdIssueMode,
      mediaPayloadRole: var_mediaPayloadRole,
    );
  }

  @protected
  MobileWatermarkError sse_decode_mobile_watermark_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_code = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return MobileWatermarkError_InvalidPayload(
          code: var_code,
          message: var_message,
        );
      case 1:
        var var_code = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        var var_existingUid = sse_decode_opt_String(deserializer);
        return MobileWatermarkError_OperationFailed(
          code: var_code,
          message: var_message,
          existingUid: var_existingUid,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MobileExtractResult? sse_decode_opt_box_autoadd_mobile_extract_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_mobile_extract_result(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_mobile_extract_result(
    MobileExtractResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mobile_extract_result(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_mobile_media_payload(
    MobileMediaPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mobile_media_payload(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_mobile_audio_result(
    MobileAudioResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
    sse_encode_String(self.watermarkUid, serializer);
    sse_encode_String(self.sha256, serializer);
  }

  @protected
  void sse_encode_mobile_extract_result(
    MobileExtractResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.watermarkUid, serializer);
    sse_encode_u_64(self.timestamp, serializer);
    sse_encode_String(self.deviceIdHex, serializer);
    sse_encode_String(self.fileHashHex, serializer);
    sse_encode_opt_String(self.parentWatermarkUid, serializer);
    sse_encode_u_32(self.revision, serializer);
    sse_encode_u_32(self.payloadProtocolVersion, serializer);
    sse_encode_u_32(self.payloadBytesLength, serializer);
    sse_encode_String(self.watermarkIdIssueMode, serializer);
    sse_encode_String(self.mediaType, serializer);
    sse_encode_String(self.payloadAuthStatus, serializer);
  }

  @protected
  void sse_encode_mobile_image_output_format(
    MobileImageOutputFormat self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_mobile_image_result(
    MobileImageResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
    sse_encode_String(self.watermarkUid, serializer);
    sse_encode_String(self.sha256, serializer);
    sse_encode_mobile_image_output_format(self.format, serializer);
  }

  @protected
  void sse_encode_mobile_media_payload(
    MobileMediaPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.creatorIdentity, serializer);
    sse_encode_String(self.deviceIdentity, serializer);
    sse_encode_list_prim_u_8_strict(self.mediaBytes, serializer);
    sse_encode_u_64(self.timestamp, serializer);
    sse_encode_opt_String(self.reservedWatermarkUid, serializer);
    sse_encode_opt_String(self.registryProofHash, serializer);
    sse_encode_opt_String(self.parentWatermarkUid, serializer);
    sse_encode_u_32(self.revision, serializer);
    sse_encode_opt_String(self.mediaType, serializer);
  }

  @protected
  void sse_encode_mobile_v_3_internal_qa_write_result(
    MobileV3InternalQaWriteResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
    sse_encode_String(self.watermarkUid, serializer);
    sse_encode_String(self.sha256, serializer);
    sse_encode_String(self.mediaType, serializer);
    sse_encode_u_32(self.payloadProtocolVersion, serializer);
    sse_encode_u_32(self.payloadBytesLength, serializer);
    sse_encode_String(self.payloadAuthStatus, serializer);
    sse_encode_String(self.watermarkIdIssueMode, serializer);
    sse_encode_String(self.mediaPayloadRole, serializer);
  }

  @protected
  void sse_encode_mobile_watermark_error(
    MobileWatermarkError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case MobileWatermarkError_InvalidPayload(
        code: final code,
        message: final message,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_String(code, serializer);
        sse_encode_String(message, serializer);
      case MobileWatermarkError_OperationFailed(
        code: final code,
        message: final message,
        existingUid: final existingUid,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(code, serializer);
        sse_encode_String(message, serializer);
        sse_encode_opt_String(existingUid, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_mobile_extract_result(
    MobileExtractResult? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_mobile_extract_result(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
