// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  IntoMobileExtractResult dco_decode_TraitDef_IntoMobileExtractResult(
    dynamic raw,
  );

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  MobileMediaPayload dco_decode_box_autoadd_mobile_media_payload(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MobileAudioResult dco_decode_mobile_audio_result(dynamic raw);

  @protected
  MobileExtractResult dco_decode_mobile_extract_result(dynamic raw);

  @protected
  MobileImageOutputFormat dco_decode_mobile_image_output_format(dynamic raw);

  @protected
  MobileImageResult dco_decode_mobile_image_result(dynamic raw);

  @protected
  MobileMediaPayload dco_decode_mobile_media_payload(dynamic raw);

  @protected
  MobileWatermarkError dco_decode_mobile_watermark_error(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  MobileMediaPayload sse_decode_box_autoadd_mobile_media_payload(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MobileAudioResult sse_decode_mobile_audio_result(
    SseDeserializer deserializer,
  );

  @protected
  MobileExtractResult sse_decode_mobile_extract_result(
    SseDeserializer deserializer,
  );

  @protected
  MobileImageOutputFormat sse_decode_mobile_image_output_format(
    SseDeserializer deserializer,
  );

  @protected
  MobileImageResult sse_decode_mobile_image_result(
    SseDeserializer deserializer,
  );

  @protected
  MobileMediaPayload sse_decode_mobile_media_payload(
    SseDeserializer deserializer,
  );

  @protected
  MobileWatermarkError sse_decode_mobile_watermark_error(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_mobile_media_payload(
    MobileMediaPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mobile_audio_result(
    MobileAudioResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mobile_extract_result(
    MobileExtractResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mobile_image_output_format(
    MobileImageOutputFormat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mobile_image_result(
    MobileImageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mobile_media_payload(
    MobileMediaPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mobile_watermark_error(
    MobileWatermarkError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
